### ISSUE TITLE
Login???

### ISSUE THREAD

**Issue by jbardi** [mcchots/homebridge-mqtt-temperature#1]
From my experience, most MQTT brokers have a login, but your plug-in assumes an open and un-secure MQTT broker. Can't use it as my server requires a login.

**Comment by mcchots** [comment]
You are correct. I have planned to add that in, but got delayed. Basic options should be added in a few days.

**Comment by mcchots** [comment]
I have added options for username and password. Can you give it a go and see if it works? 
I don't have MQTT authentication setup as yet on my test machine.
