### ISSUE TITLE
Temperature accuracy

### ISSUE THREAD

**Issue by M4RC02U1F4A4** [mcchots/homebridge-mqtt-temperature#12]
Hi, now with IOS 12 it seems like the Home app has more accuracy on the misuration. Is there some way to use all the data red from my sensor instead of approximate them?
![photo_2018-09-21_17-04-38](https://user-images.githubusercontent.com/23193188/45889398-a4bcb080-bdc0-11e8-8ee3-76cd2698f211.jpg)

![cattura](https://user-images.githubusercontent.com/23193188/45889363-8c4c9600-bdc0-11e8-8bb7-34676f1404d8.PNG)

**Comment by mcchots** [comment]
Unfortunately from my testing, this is an issue with the Home app. It seems that Apple only rounds to the nearest 5. 

So your temperature gets rounded down to 28.0. 
My current temperature of 22.4135 as broadcast is shown as 22.5 in Home and 22.4 in the Eve app.
