### ISSUE TITLE
values are "stuck" at some old values

### ISSUE THREAD

**Issue by aleksandrsivanovs** [mcchots/homebridge-mqtt-temperature#13]
hi!

as described here: https://github.com/nfarina/homebridge/issues/2021

after sometime the values are sticking to some old values and does not update.
only homebridge restart helps.

might be, there is some problems with mqtt client itself?

**Comment by mcchots** [comment]
Hi Alexandrs,

Maybe a problem with mqtt disconnecting and not reconnecting. 
Do you have a debug log?

**Comment by mcchots** [comment]
Closing this as I can't replicate.
