### ISSUE TITLE
sensor greyed out in automation 

### ISSUE THREAD

**Issue by arjena** [mcchots/homebridge-mqtt-temperature#6]
I'm using this plugin to display the outdoor temperature. Works great. But in the Home app on my phone it is apparently not seen as a sensor, sensors are greyed out as a trigger. 
Any ideas as to why?

**Comment by mcchots** [comment]
How does it show up for you?

**Comment by arjena** [comment]
In my home screen in the 'Home' app it is has a sensor icon (square with three vertical stripes in the top-right corner). The temperature is displayed properly. I can use it as a trigger in Elgato Eve, but in the Home app when I choose 'new automation', I can trigger on location, time and accessory. Sensor(s) are also mentioned but greyed out. When I click on accessory, it only shows the switches, not the sensor. So I cannot use the value of the temp sensor to turn on something. Maybe this is always the case with sensors, I'm fairly new to all of this. But since the Elgato app does see the sensor as a trigger, I was just wondering what I'm missing...

![homescreendump](https://cloud.githubusercontent.com/assets/5932518/22601643/16e92eb4-ea40-11e6-9cf0-ec3b3985527d.png)

**Comment by mcchots** [comment]
From this article on Elgato's blog [iOS 10 and Homekit](https://blog.elgato.com/ios-10-and-homekit/) it appears that Home does not support value triggers other than Contact and Power. 

Unfortunately, I cannot even test this as I do not have an Apple TV or iPad with iOS 10

**Comment by arjena** [comment]
Well, take my word for it, they are right... I can easily re-write the plugin to make it a Contact so it cab trigger things, or just keep using the Elgato app for this. Thanks for your help,

A

**Comment by arjena** [comment]
Re-reading my last comment I found it might come over as sarcastic. It is not. I am genuinely grateful for your work on this plugin and the fact that you take time to respond to my question. So thanks again,

A
