### ISSUE TITLE
Improve - Battery Info

### ISSUE THREAD

**Issue by GerSant** [mcchots/homebridge-mqtt-temperature#8]
Hi, its possible to add the new battery service/battery info to this plugin as optional, one parameter more to specify, thorough a mqtt topic, the battery percentaje of our accesory (same for homebridge-mqtt-humidity)

Thanks!

**Comment by mcchots** [comment]
I have implemented BatteryLevel and LowBatteryStatus in the latest [0.60 release](https://www.npmjs.com/package/homebridge-mqtt-temperature).
Will hopefully update the humidity plugin in a few days.

[Reference 26860f0838e893410a99e263e38e1aabd06bbc85]

**Comment by GerSant** [comment]
Thank you very much! Thats great improvement!
